language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install ruby rake bison git
script:
  - MRUBY_CONFIG=.travis_build_config.rb rake test
